services:
  # Backend service
  server:
    image: node:18
    container_name: parcel-management-server
    working_dir: /app
    command: >
      bash -c "
        npm install &&
        apt-get update && 
        apt-get install -y python3 make g++ && 
        npm rebuild sqlite3 --build-from-source && 
        node startup.js"
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - /app/node_modules
      - db-data:/app/data
      - uploads-data:/app/uploads
    environment:
      - PORT=8000
      - NODE_ENV=development
      - JWT_SECRET=your_jwt_secret_key
      - PUBLIC_URL=http://localhost:8000
    networks:
      - app-network

  # Frontend service
  client:
    image: node:18
    container_name: parcel-management-client
    working_dir: /app
    command: >
      bash -c "npm install && npm run dev"
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://localhost:8000

volumes:
  db-data:
    driver: local
  uploads-data:
    driver: local

networks:
  app-network:
    driver: bridge 
